### PR TITLE
improve ClasspathUtilCore.getPath performance eclipse-pde#13

### PR DESCRIPTION
**Pull request by jukzi**
isAbsolute() is cheap, exists() is I/O. fail fast!

### CODE REVIEW

**Comment by HannesWell** [comment]
> Looks good. Will merge after m1 has been released

I can only agree with this.

> isAbsolute() is cheap, exists() is I/O. fail fast!

Thank you Jörg. I/O is indeed very often surprisingly slow and I already noticed it multiple times that devlopers are not aware of it (at least the write code like the one you have corrected).
But when you have to do I/O it can also make a big difference how you do it.
For example `File.copy()` is in my experience magnitudes faster (in my case, it was about 200 times) than transferring a `FileInputStream` to an `FileOutputStream`.

**Comment by jukzi** [comment]
superseeded by 
https://github.com/eclipse-pde/eclipse.pde.ui/pull/15

**Comment by mickaelistria** [comment]
> superseeded by https://github.com/eclipse-pde/eclipse.pde.ui/pull/15

So should we close this one?

**Comment by EclipseNewb** [comment]
> So should we close this one?

if you agree to merge #15 instead- yes!

**Comment by mickaelistria** [comment]
#15 looks good to me to be merged as soon as M1 is complete. So let's close this one.

**Pull request closed without merging**
